---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server-collector
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: server-collector
    spec:
      containers:
      - name: server-collector
        image: rickming/server-collector:0.0.4
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: server-collector-conf
        volumeMounts:
        - mountPath: /var/run
          name: shutdown-signal
      volumes:
      - name: shutdown-signal
        hostPath:
          path: /var/run
          type: Directory
---
apiVersion: v1
data:
  TARGET_SERVER: "127.0.0.1"
  ACCESS_TOKEN: "495fe0558bb01d3635bfa9e93f5ebecc83f85387"
  SOURCE_OWNER: "lmchih"
  SOURCE_REPO: "server-collector"
  SOURCE_BRANCH: "master"
  CHECK_FREQUENCY: "120"
  UNUSED_DAYS: "3"
kind: ConfigMap
metadata:
  name: server-collector-conf
---
